Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -47,16 +47,18 @@ jobs:
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
-            ZIP_NAME=django_rest_${{ github.sha }}.zip
+            script: |
+              ZIP_NAME=django_rest_${{ github.sha }}.zip
+            
+              echo "📦 Downloading $ZIP_NAME from S3..."
+              aws s3 cp s3://${{ env.S3_BUCKET_NAME }}/$ZIP_NAME /home/ec2-user/
+            
+              echo "📂 Unzipping package..."
+              mkdir -p /home/ec2-user/app/
+              unzip -o /home/ec2-user/$ZIP_NAME -d /home/ec2-user/app/ || { echo "❌ Failed to unzip"; exit 1; }
+            
+              echo "🛠 Running deploy script..."
+              cd /home/ec2-user/app/core
+              chmod +x deploy.sh
+              bash deploy.sh
 
-            echo "📦 Downloading from S3..."
-            aws s3 cp s3://${{ env.S3_BUCKET_NAME }}/$ZIP_NAME /home/${{ secrets.EC2_USER }}/
-
-            echo "📂 Unzipping..."
-            rm -rf /home/${{ secrets.EC2_USER }}/app/
-            mkdir -p /home/${{ secrets.EC2_USER }}/app/
-            unzip -o /home/${{ secrets.EC2_USER }}/$ZIP_NAME -d /home/${{ secrets.EC2_USER }}/app/
-
-            echo "🚀 Running deploy script..."
-            chmod +x /home/${{ secrets.EC2_USER }}/app/deploy.sh
-            bash /home/${{ secrets.EC2_USER }}/app/deploy.sh
